"""LUME CREATORS: public landing, private admin and persistent creator records."""

from __future__ import annotations

import argparse
import csv
import getpass
import hashlib
import hmac
import io
import json
import os
import re
import secrets
import sqlite3
import threading
import time
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse, Response


ROOT = Path(__file__).resolve().parent
DATA_DIR = Path(os.getenv("LUME_DATA_DIR", ROOT / "data")).resolve()
DB_PATH = DATA_DIR / "lume.sqlite3"
VIDEO_PATH = DATA_DIR / "campaign.mp4"
IS_VERCEL = bool(os.getenv("VERCEL"))
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
VIDEO_URL = os.getenv("LUME_VIDEO_URL", "").strip()
DEV_HTTP = os.getenv("LUME_DEV_HTTP") == "1" and not IS_VERCEL
SESSION_SECONDS = 12 * 60 * 60
MAX_CONFIG_BYTES = 1_000_000
MAX_VIDEO_BYTES = 250 * 1024 * 1024
STATUSES = {"novo", "contatado", "fechado", "divulgando", "concluido", "nao_divulgou", "recusado"}
LOGIN_ATTEMPTS: dict[str, list[float]] = {}
LEAD_ATTEMPTS: dict[str, list[float]] = {}
SETUP_ATTEMPTS: dict[str, list[float]] = {}
_SCHEMA_READY = False
_SCHEMA_LOCK = threading.Lock()


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class PostgresDatabase:
    """Keep the existing parameterized SQLite queries usable with Psycopg."""

    def __init__(self, connection):
        self.connection = connection

    def execute(self, statement: str, parameters=()):
        return self.connection.execute(statement.replace("?", "%s"), parameters)

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()


@contextmanager
def _raw_database():
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        connection = psycopg.connect(DATABASE_URL, row_factory=dict_row, connect_timeout=10)
        db = PostgresDatabase(connection)
    else:
        if IS_VERCEL:
            raise HTTPException(503, "Configure DATABASE_URL com um PostgreSQL persistente antes de publicar.")
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(DB_PATH, timeout=15)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute("PRAGMA journal_mode = WAL")
        db = connection
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        connection.close()


@contextmanager
def database():
    if not _SCHEMA_READY:
        init_database()
    with _raw_database() as db:
        yield db


def init_database() -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return
    with _SCHEMA_LOCK:
        if _SCHEMA_READY:
            return
        with _raw_database() as db:
            if DATABASE_URL:
                db.execute("SELECT pg_advisory_xact_lock(687543210)")
                for statement in (
                    """CREATE TABLE IF NOT EXISTS admin_users (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      email TEXT NOT NULL UNIQUE,
                      display_name TEXT NOT NULL DEFAULT '',
                      password_salt TEXT NOT NULL,
                      password_hash TEXT NOT NULL,
                      totp_secret TEXT NOT NULL,
                      last_totp_step BIGINT NOT NULL DEFAULT -1,
                      failed_attempts INTEGER NOT NULL DEFAULT 0,
                      locked_until BIGINT NOT NULL DEFAULT 0
                    )""",
                    """CREATE TABLE IF NOT EXISTS sessions (
                      token_hash TEXT PRIMARY KEY,
                      admin_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
                      csrf_token TEXT NOT NULL,
                      expires_at BIGINT NOT NULL
                    )""",
                    "CREATE TABLE IF NOT EXISTS config (key TEXT PRIMARY KEY, value TEXT NOT NULL)",
                    """CREATE TABLE IF NOT EXISTS creators (
                      id TEXT PRIMARY KEY,
                      legacy_id TEXT UNIQUE,
                      created_at TEXT NOT NULL,
                      source TEXT NOT NULL,
                      name TEXT NOT NULL DEFAULT '',
                      instagram TEXT NOT NULL,
                      followers TEXT NOT NULL DEFAULT '',
                      stories TEXT NOT NULL DEFAULT '',
                      experience TEXT NOT NULL DEFAULT '',
                      status TEXT NOT NULL DEFAULT 'novo',
                      valid_depositors INTEGER NOT NULL DEFAULT 0,
                      revenue_cents BIGINT NOT NULL DEFAULT 0,
                      payout_cents BIGINT NOT NULL DEFAULT 0,
                      notes TEXT NOT NULL DEFAULT '',
                      attribution_json TEXT NOT NULL DEFAULT '{}',
                      device_json TEXT NOT NULL DEFAULT '{}'
                    )""",
                    "CREATE INDEX IF NOT EXISTS creators_status_idx ON creators(status)",
                    "CREATE INDEX IF NOT EXISTS creators_created_idx ON creators(created_at DESC)",
                    """CREATE TABLE IF NOT EXISTS rate_limits (
                      bucket TEXT NOT NULL,
                      identifier TEXT NOT NULL,
                      attempts INTEGER NOT NULL,
                      started_at BIGINT NOT NULL,
                      PRIMARY KEY (bucket, identifier)
                    )""",
                    "CREATE INDEX IF NOT EXISTS rate_limits_started_idx ON rate_limits(started_at)",
                    "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT ''",
                ):
                    db.execute(statement)
            else:
                db.executescript(
            """
            CREATE TABLE IF NOT EXISTS admin_users (
              id INTEGER PRIMARY KEY,
              email TEXT NOT NULL UNIQUE,
              display_name TEXT NOT NULL DEFAULT '',
              password_salt TEXT NOT NULL,
              password_hash TEXT NOT NULL,
              totp_secret TEXT NOT NULL,
              last_totp_step INTEGER NOT NULL DEFAULT -1,
              failed_attempts INTEGER NOT NULL DEFAULT 0,
              locked_until INTEGER NOT NULL DEFAULT 0
            );
            CREATE TABLE IF NOT EXISTS sessions (
              token_hash TEXT PRIMARY KEY,
              admin_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
              csrf_token TEXT NOT NULL,
              expires_at INTEGER NOT NULL
            );
            CREATE TABLE IF NOT EXISTS config (
              key TEXT PRIMARY KEY,
              value TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS creators (
              id TEXT PRIMARY KEY,
              legacy_id TEXT UNIQUE,
              created_at TEXT NOT NULL,
              source TEXT NOT NULL,
              name TEXT NOT NULL DEFAULT '',
              instagram TEXT NOT NULL,
              followers TEXT NOT NULL DEFAULT '',
              stories TEXT NOT NULL DEFAULT '',
              experience TEXT NOT NULL DEFAULT '',
              status TEXT NOT NULL DEFAULT 'novo',
              valid_depositors INTEGER NOT NULL DEFAULT 0,
              revenue_cents INTEGER NOT NULL DEFAULT 0,
              payout_cents INTEGER NOT NULL DEFAULT 0,
              notes TEXT NOT NULL DEFAULT '',
              attribution_json TEXT NOT NULL DEFAULT '{}',
              device_json TEXT NOT NULL DEFAULT '{}'
            );
            CREATE INDEX IF NOT EXISTS creators_status_idx ON creators(status);
            CREATE INDEX IF NOT EXISTS creators_created_idx ON creators(created_at DESC);
            """
                )
                columns = {row["name"] for row in db.execute("PRAGMA table_info(admin_users)")}
                if "display_name" not in columns:
                    db.execute("ALTER TABLE admin_users ADD COLUMN display_name TEXT NOT NULL DEFAULT ''")
        _SCHEMA_READY = True


def password_hash(password: str, salt: bytes) -> str:
    return hashlib.scrypt(password.encode("utf-8"), salt=salt, n=2**15, r=8, p=1, dklen=32, maxmem=64 * 1024 * 1024).hex()


def bootstrap_admin(email: str) -> None:
    init_database()
    email = email.strip().lower()
    if not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", email):
        raise SystemExit("Informe um e-mail válido.")
    with database() as db:
        if db.execute("SELECT 1 FROM admin_users WHERE email = ?", (email,)).fetchone():
            raise SystemExit("Esse administrador já existe.")
    password = getpass.getpass("Nova senha (mínimo 8 caracteres): ")
    if len(password) < 8:
        raise SystemExit("A senha precisa ter pelo menos 8 caracteres.")
    if not hmac.compare_digest(password, getpass.getpass("Repita a senha: ")):
        raise SystemExit("As senhas não conferem.")
    salt = secrets.token_bytes(16)
    with database() as db:
        db.execute(
            "INSERT INTO admin_users(email,display_name,password_salt,password_hash,totp_secret) VALUES(?,?,?,?,?)",
            (email, email.split("@")[0], salt.hex(), password_hash(password, salt), ""),
        )
    print("Administrador criado. Acesse /admin/login/.")


def get_session(request: Request) -> sqlite3.Row | dict | None:
    token = request.cookies.get("lume_session", "")
    if not re.fullmatch(r"[a-f0-9]{64}", token):
        return None
    with database() as db:
        return db.execute(
            """SELECT sessions.*, admin_users.email, admin_users.display_name FROM sessions
               JOIN admin_users ON admin_users.id = sessions.admin_id
               WHERE token_hash = ? AND expires_at > ?""",
            (hashlib.sha256(token.encode()).hexdigest(), int(time.time())),
        ).fetchone()


def require_session(request: Request) -> sqlite3.Row | dict:
    session = get_session(request)
    if session is None:
        raise HTTPException(401, "Faça login no painel.")
    return session


def same_origin(request: Request) -> bool:
    origin = request.headers.get("origin")
    if not origin:
        return True
    return urlparse(origin).netloc.lower() == request.headers.get("host", "").lower()


def require_write(request: Request) -> sqlite3.Row | dict:
    session = require_session(request)
    if not same_origin(request) or not hmac.compare_digest(
        request.headers.get("x-csrf-token", ""), session["csrf_token"]
    ):
        raise HTTPException(403, "Recarregue o painel e tente novamente.")
    return session


def rate_limited(bucket: dict[str, list[float]], key: str, limit: int, window: int) -> bool:
    if DATABASE_URL:
        bucket_name = "login" if bucket is LOGIN_ATTEMPTS else "setup" if bucket is SETUP_ATTEMPTS else "lead"
        now = int(time.time())
        with database() as db:
            row = db.execute(
                """INSERT INTO rate_limits(bucket,identifier,attempts,started_at) VALUES(?,?,1,?)
                   ON CONFLICT(bucket,identifier) DO UPDATE SET
                     attempts=CASE WHEN rate_limits.started_at <= ? THEN 1 ELSE rate_limits.attempts+1 END,
                     started_at=CASE WHEN rate_limits.started_at <= ? THEN ? ELSE rate_limits.started_at END
                   RETURNING attempts""",
                (bucket_name, key, now, now - window, now - window, now),
            ).fetchone()
            if secrets.randbelow(100) == 0:
                db.execute("DELETE FROM rate_limits WHERE started_at < ?", (now - 86400,))
        return row["attempts"] > limit
    now = time.monotonic()
    attempts = [moment for moment in bucket.get(key, []) if now - moment < window]
    bucket[key] = attempts
    if len(attempts) >= limit:
        return True
    attempts.append(now)
    return False


def client_ip(request: Request) -> str:
    if IS_VERCEL:
        # Vercel replaces this header before the request reaches the Function.
        return request.headers.get("x-vercel-forwarded-for", "unknown").split(",", 1)[0].strip()[:128]
    # Do not trust X-Forwarded-For from an arbitrary local client.
    return request.client.host if request.client else "unknown"


def has_admin() -> bool:
    with database() as db:
        return db.execute("SELECT 1 FROM admin_users LIMIT 1").fetchone() is not None


def local_setup_allowed(request: Request) -> bool:
    return DEV_HTTP and request.url.hostname in {"127.0.0.1", "localhost", "::1"} and client_ip(request) in {"127.0.0.1", "::1"}


def require_setup_access(request: Request, setup_key: str) -> None:
    if has_admin():
        raise HTTPException(409, "O cadastro inicial já foi concluído.")
    if local_setup_allowed(request):
        return
    configured_key = os.getenv("LUME_SETUP_TOKEN", "")
    if len(configured_key) < 24:
        raise HTTPException(503, "Configure LUME_SETUP_TOKEN com pelo menos 24 caracteres no servidor para criar a primeira conta.")
    if not hmac.compare_digest(setup_key, configured_key):
        raise HTTPException(403, "Chave de configuração inválida.")


def new_session_response(db, admin_id: int) -> JSONResponse:
    token = secrets.token_hex(32)
    csrf = secrets.token_urlsafe(32)
    db.execute("DELETE FROM sessions WHERE expires_at <= ?", (int(time.time()),))
    db.execute("INSERT INTO sessions VALUES(?,?,?,?)", (hashlib.sha256(token.encode()).hexdigest(), admin_id, csrf, int(time.time()) + SESSION_SECONDS))
    response = JSONResponse({"ok": True})
    response.set_cookie("lume_session", token, max_age=SESSION_SECONDS, httponly=True, secure=not DEV_HTTP, samesite="strict", path="/")
    return response


def read_config() -> dict:
    with database() as db:
        row = db.execute("SELECT value FROM config WHERE key='site'").fetchone()
    return json.loads(row["value"]) if row else {}


def script_json(value: dict) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def html_with_state(path: Path, state: dict, nonce: str) -> HTMLResponse:
    html = path.read_text(encoding="utf-8")
    injected = f'<script nonce="{nonce}">window.LUME_BACKEND=true;Object.assign(window,{script_json(state)});</script>'
    return HTMLResponse(html.replace("</head>", injected + "\n</head>", 1))


def creator_dict(row: sqlite3.Row | dict) -> dict:
    result = dict(row)
    result["attribution"] = json.loads(result.pop("attribution_json"))
    result["device"] = json.loads(result.pop("device_json"))
    return result


async def limited_json(request: Request, max_bytes: int = 64_000) -> dict:
    if request.headers.get("content-type", "").split(";", 1)[0] != "application/json":
        raise HTTPException(415, "Envie JSON.")
    if int(request.headers.get("content-length") or 0) > max_bytes:
        raise HTTPException(413, "Dados grandes demais.")
    body = await request.body()
    if len(body) > max_bytes:
        raise HTTPException(413, "Dados grandes demais.")
    try:
        payload = json.loads(body)
    except (json.JSONDecodeError, UnicodeDecodeError):
        raise HTTPException(400, "JSON inválido.") from None
    if not isinstance(payload, dict):
        raise HTTPException(400, "Formato inválido.")
    return payload


app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)
app.add_middleware(GZipMiddleware, minimum_size=1024)
if not IS_VERCEL:
    init_database()


@app.middleware("http")
async def security_headers(request: Request, call_next):
    nonce = secrets.token_urlsafe(18)
    request.state.nonce = nonce
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    response.headers["Content-Security-Policy"] = (
        "default-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; "
        "form-action 'self'; script-src 'self' 'nonce-" + nonce + "' "
        "https://www.googletagmanager.com https://connect.facebook.net; "
        "style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; "
        "connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://connect.facebook.net; "
        "frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://drive.google.com; media-src 'self' https:"
    )
    if request.url.path.startswith(("/admin", "/api/admin", "/api/auth", "/api/setup")):
        response.headers["Cache-Control"] = "no-store"
    if not DEV_HTTP:
        response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
    return response


@app.get("/healthz")
def health():
    with database() as db:
        db.execute("SELECT 1")
    return {"ok": True}


@app.get("/")
@app.get("/index.html")
def landing(request: Request):
    return html_with_state(ROOT / "index.html", {"LUME_SERVER_CONFIG": read_config()}, request.state.nonce)


@app.get("/admin/login/")
@app.get("/admin/login/index.html")
def login_page(request: Request):
    if get_session(request):
        return RedirectResponse("/admin/", status_code=302)
    if not has_admin():
        return RedirectResponse("/admin/setup/", status_code=302)
    return FileResponse(ROOT / "admin" / "login.html", headers={"Cache-Control": "no-store"})


@app.get("/admin/setup/")
@app.get("/admin/setup/index.html")
def setup_page(request: Request):
    if has_admin():
        return RedirectResponse("/admin/login/", status_code=302)
    return FileResponse(ROOT / "admin" / "setup.html", headers={"Cache-Control": "no-store"})


@app.get("/admin/")
@app.get("/admin/index.html")
def admin_page(request: Request):
    session = get_session(request)
    if not session:
        return RedirectResponse("/admin/login/", status_code=302)
    return html_with_state(
        ROOT / "admin" / "index.html",
        {"LUME_ADMIN_CONFIG": read_config(), "LUME_CSRF": session["csrf_token"], "LUME_ADMIN_EMAIL": session["email"], "LUME_ADMIN_NAME": session["display_name"],
         "LUME_EXTERNAL_VIDEO_ONLY": IS_VERCEL, "LUME_EXTERNAL_VIDEO_CONFIGURED": bool(VIDEO_URL)},
        request.state.nonce,
    )


@app.get("/{filename}")
def root_asset(filename: str, request: Request):
    public = {"styles.css", "app.js", "motion.js", "feedback-data.js"}
    private = {"admin.css", "admin.js"}
    login_assets = {"login.css", "login.js", "setup.css", "setup.js"}
    if filename in private and not get_session(request):
        raise HTTPException(404)
    if filename in login_assets:
        return FileResponse(ROOT / "admin" / filename, headers={"Cache-Control": "no-store"})
    if filename not in public | private:
        raise HTTPException(404)
    return FileResponse(ROOT / filename, headers={"Cache-Control": "public, max-age=3600" if filename in public else "no-store"})


@app.get("/assets/{asset_path:path}")
def assets(asset_path: str):
    asset_root = (ROOT / "assets").resolve()
    file_path = (asset_root / asset_path).resolve()
    if not file_path.is_relative_to(asset_root) or not file_path.is_file():
        raise HTTPException(404)
    return FileResponse(file_path, headers={"Cache-Control": "public, max-age=86400"})


@app.get("/api/setup/status")
def setup_status(request: Request):
    available = not has_admin()
    local = local_setup_allowed(request)
    return {
        "available": available,
        "requires_key": available and not local,
        "key_configured": bool(local or len(os.getenv("LUME_SETUP_TOKEN", "")) >= 24),
    }


@app.post("/api/setup/start")
async def setup_start(request: Request):
    if not same_origin(request):
        raise HTTPException(403, "Origem inválida.")
    if rate_limited(SETUP_ATTEMPTS, client_ip(request), 8, 1800):
        raise HTTPException(429, "Muitas tentativas. Aguarde alguns minutos.")
    payload = await limited_json(request, 4_000)
    setup_key = str(payload.get("setup_key", ""))[:512]
    require_setup_access(request, setup_key)
    email = str(payload.get("email", "")).strip().lower()[:254]
    display_name = str(payload.get("display_name", "")).strip()[:80]
    password = str(payload.get("password", ""))
    if not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", email):
        raise HTTPException(400, "Informe um e-mail válido.")
    if len(display_name) < 2:
        raise HTTPException(400, "Informe seu nome.")
    if len(password) < 8 or len(password) > 512:
        raise HTTPException(400, "A senha precisa ter entre 8 e 512 caracteres.")
    salt = secrets.token_bytes(16)
    with database() as db:
        if DATABASE_URL:
            db.execute("SELECT pg_advisory_xact_lock(687543211)")
        else:
            db.execute("BEGIN IMMEDIATE")
        if db.execute("SELECT 1 FROM admin_users LIMIT 1").fetchone():
            raise HTTPException(409, "O cadastro inicial já foi concluído.")
        cursor = db.execute(
            """INSERT INTO admin_users(email,display_name,password_salt,password_hash,totp_secret)
               VALUES(?,?,?,?,?) RETURNING id""",
            (email, display_name, salt.hex(), password_hash(password, salt), ""),
        )
        return new_session_response(db, cursor.fetchone()["id"])


@app.post("/api/auth/login")
async def login(request: Request):
    if not same_origin(request):
        raise HTTPException(403, "Origem inválida.")
    key = client_ip(request)
    if rate_limited(LOGIN_ATTEMPTS, key, 12, 900):
        raise HTTPException(429, "Muitas tentativas. Tente novamente em alguns minutos.")
    payload = await limited_json(request, 4_000)
    email = str(payload.get("email", "")).strip().lower()[:254]
    password = str(payload.get("password", ""))[:512]
    with database() as db:
        statement = "SELECT * FROM admin_users WHERE email = ?"
        if DATABASE_URL:
            statement += " FOR UPDATE"
        user = db.execute(statement, (email,)).fetchone()
        if not user or user["locked_until"] > int(time.time()):
            raise HTTPException(401, "E-mail ou senha inválidos.")
        expected = password_hash(password, bytes.fromhex(user["password_salt"]))
        if not hmac.compare_digest(expected, user["password_hash"]):
            failures = user["failed_attempts"] + 1
            locked_until = int(time.time()) + 900 if failures >= 5 else 0
            db.execute("UPDATE admin_users SET failed_attempts=?, locked_until=? WHERE id=?", (failures if failures < 5 else 0, locked_until, user["id"]))
            db.commit()
            raise HTTPException(401, "E-mail ou senha inválidos.")
        db.execute("UPDATE admin_users SET failed_attempts=0, locked_until=0 WHERE id=?", (user["id"],))
        return new_session_response(db, user["id"])


@app.get("/api/auth/session")
def session_info(request: Request):
    session = get_session(request)
    return {"authenticated": bool(session), "email": session["email"] if session else None, "csrf": session["csrf_token"] if session else None}


@app.post("/api/auth/logout")
def logout(request: Request):
    require_write(request)
    token = request.cookies.get("lume_session", "")
    with database() as db:
        db.execute("DELETE FROM sessions WHERE token_hash = ?", (hashlib.sha256(token.encode()).hexdigest(),))
    response = JSONResponse({"ok": True})
    response.delete_cookie("lume_session", path="/")
    return response


@app.get("/api/admin/config")
def admin_config(request: Request):
    require_session(request)
    return read_config()


@app.put("/api/admin/config")
async def save_config(request: Request):
    require_write(request)
    payload = await limited_json(request, MAX_CONFIG_BYTES)
    if not all(isinstance(payload.get(name), dict) for name in ("campaign", "content", "vsl", "analytics", "legal")):
        raise HTTPException(400, "Configuração incompleta.")
    number = re.sub(r"\D", "", str(payload["campaign"].get("whatsapp", "")))
    if number and not re.fullmatch(r"\d{12,15}", number):
        raise HTTPException(400, "WhatsApp precisa incluir DDI e DDD.")
    payload["campaign"]["whatsapp"] = number
    with database() as db:
        db.execute("INSERT INTO config(key,value) VALUES('site',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value", (json.dumps(payload, ensure_ascii=False),))
    return {"ok": True}


@app.post("/api/leads")
async def create_lead(request: Request):
    if not same_origin(request):
        raise HTTPException(403, "Origem inválida.")
    if rate_limited(LEAD_ATTEMPTS, client_ip(request), 15, 3600):
        raise HTTPException(429, "Muitas tentativas. Tente mais tarde.")
    payload = await limited_json(request, 16_000)
    instagram = str(payload.get("instagram", "")).strip()
    if not re.fullmatch(r"@[A-Za-z0-9._]{2,30}", instagram):
        raise HTTPException(400, "Instagram inválido.")
    answers = payload.get("answers") if isinstance(payload.get("answers"), dict) else {}
    attribution = payload.get("attribution") if isinstance(payload.get("attribution"), dict) else {}
    device = payload.get("device") if isinstance(payload.get("device"), dict) else {}
    creator_id = uuid.uuid4().hex
    with database() as db:
        db.execute(
            """INSERT INTO creators(id,created_at,source,instagram,followers,stories,experience,attribution_json,device_json)
               VALUES(?,?,?,?,?,?,?,?,?)""",
            (creator_id, now_iso(), "quiz", instagram, str(answers.get("question_1", ""))[:80],
             str(answers.get("question_2", ""))[:80], str(answers.get("question_3", ""))[:80],
             json.dumps(attribution, ensure_ascii=False)[:4000], json.dumps(device, ensure_ascii=False)[:4000]),
        )
    return JSONResponse({"ok": True, "id": creator_id}, status_code=201)


@app.get("/api/admin/creators")
def list_creators(request: Request):
    require_session(request)
    with database() as db:
        rows = db.execute("SELECT * FROM creators ORDER BY created_at DESC LIMIT 5000").fetchall()
    return {"creators": [creator_dict(row) for row in rows]}


@app.post("/api/admin/creators")
async def add_creator(request: Request):
    require_write(request)
    payload = await limited_json(request, 8_000)
    instagram = str(payload.get("instagram", "")).strip().lstrip("@")
    if not re.fullmatch(r"[A-Za-z0-9._]{2,30}", instagram):
        raise HTTPException(400, "Informe um Instagram válido.")
    creator_id = uuid.uuid4().hex
    status = str(payload.get("status", "novo"))
    if status not in STATUSES:
        raise HTTPException(400, "Situação inválida.")
    numbers = {}
    for key in ("valid_depositors", "revenue_cents", "payout_cents"):
        value = payload.get(key, 0)
        if isinstance(value, bool) or not isinstance(value, int) or value < 0 or value > 1_000_000_000:
            raise HTTPException(400, "Valor numérico inválido.")
        numbers[key] = value
    with database() as db:
        db.execute(
            """INSERT INTO creators(id,created_at,source,name,instagram,followers,status,notes,
               valid_depositors,revenue_cents,payout_cents) VALUES(?,?,?,?,?,?,?,?,?,?,?)""",
            (creator_id, now_iso(), "manual", str(payload.get("name", "")).strip()[:120], "@" + instagram,
             str(payload.get("followers", "")).strip()[:80], status, str(payload.get("notes", "")).strip()[:2000],
             numbers["valid_depositors"], numbers["revenue_cents"], numbers["payout_cents"]),
        )
        row = db.execute("SELECT * FROM creators WHERE id=?", (creator_id,)).fetchone()
    return JSONResponse(creator_dict(row), status_code=201)


@app.patch("/api/admin/creators/{creator_id}")
async def update_creator(creator_id: str, request: Request):
    require_write(request)
    payload = await limited_json(request, 8_000)
    allowed_text = {"name": 120, "followers": 80, "notes": 2000}
    allowed_int = {"valid_depositors", "revenue_cents", "payout_cents"}
    updates = {}
    for key, limit in allowed_text.items():
        if key in payload:
            updates[key] = str(payload[key]).strip()[:limit]
    for key in allowed_int:
        if key in payload:
            value = payload[key]
            if isinstance(value, bool) or not isinstance(value, int) or value < 0 or value > 1_000_000_000:
                raise HTTPException(400, "Valor numérico inválido.")
            updates[key] = value
    if "status" in payload:
        if payload["status"] not in STATUSES:
            raise HTTPException(400, "Situação inválida.")
        updates["status"] = payload["status"]
    if not updates:
        raise HTTPException(400, "Nenhuma alteração enviada.")
    columns = ", ".join(f"{key}=?" for key in updates)
    with database() as db:
        cursor = db.execute(f"UPDATE creators SET {columns} WHERE id=?", (*updates.values(), creator_id))
        if cursor.rowcount == 0:
            raise HTTPException(404, "Creator não encontrado.")
        row = db.execute("SELECT * FROM creators WHERE id=?", (creator_id,)).fetchone()
    return creator_dict(row)


@app.delete("/api/admin/creators/{creator_id}")
def delete_creator(creator_id: str, request: Request):
    require_write(request)
    with database() as db:
        result = db.execute("DELETE FROM creators WHERE id=?", (creator_id,))
        if result.rowcount == 0:
            raise HTTPException(404, "Creator não encontrado.")
    return {"ok": True}


@app.post("/api/admin/import-leads")
async def import_local_leads(request: Request):
    require_write(request)
    payload = await limited_json(request, MAX_CONFIG_BYTES)
    leads = payload.get("leads")
    if not isinstance(leads, list) or len(leads) > 1000:
        raise HTTPException(400, "Lista inválida.")
    added = 0
    with database() as db:
        for lead in leads:
            if not isinstance(lead, dict):
                continue
            instagram = str(lead.get("instagram", ""))[:32]
            if not re.fullmatch(r"@[A-Za-z0-9._]{2,30}", instagram):
                continue
            answers = lead.get("answers") if isinstance(lead.get("answers"), dict) else {}
            cursor = db.execute(
                """INSERT INTO creators(id,legacy_id,created_at,source,instagram,followers,stories,experience,attribution_json,device_json)
                   VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING""",
                (uuid.uuid4().hex, str(lead.get("id", ""))[:120] or None, str(lead.get("createdAt", ""))[:40] or now_iso(),
                 "quiz", instagram, str(answers.get("question_1", ""))[:80], str(answers.get("question_2", ""))[:80],
                 str(answers.get("question_3", ""))[:80], json.dumps(lead.get("attribution") or {}, ensure_ascii=False)[:4000],
                 json.dumps(lead.get("device") or {}, ensure_ascii=False)[:4000]),
            )
            added += cursor.rowcount
    return {"ok": True, "added": added}


@app.get("/api/admin/dashboard")
def dashboard(request: Request):
    require_session(request)
    with database() as db:
        row = db.execute(
            """SELECT COUNT(*) AS total,
               SUM(CASE WHEN status IN ('fechado','divulgando','concluido') THEN 1 ELSE 0 END) AS closed,
               SUM(CASE WHEN status='divulgando' THEN 1 ELSE 0 END) AS running,
               SUM(CASE WHEN status='nao_divulgou' THEN 1 ELSE 0 END) AS did_not_post,
               SUM(valid_depositors) AS depositors,
               SUM(revenue_cents) AS revenue_cents,
               SUM(payout_cents) AS payout_cents FROM creators"""
        ).fetchone()
    data = {key: row[key] or 0 for key in row.keys()}
    data["balance_cents"] = data["revenue_cents"] - data["payout_cents"]
    return data


@app.get("/api/admin/export.csv")
def export_csv(request: Request):
    require_session(request)
    with database() as db:
        rows = db.execute("SELECT * FROM creators ORDER BY created_at DESC").fetchall()
    output = io.StringIO()
    writer = csv.writer(output)
    columns = ("created_at", "source", "name", "instagram", "followers", "stories", "experience", "status", "valid_depositors", "revenue_cents", "payout_cents", "notes")
    writer.writerow(columns)
    for row in rows:
        writer.writerow([csv_safe(row[key]) for key in columns])
    return Response("\ufeff" + output.getvalue(), media_type="text/csv; charset=utf-8", headers={"Content-Disposition": 'attachment; filename="lume-creators.csv"'})


def csv_safe(value):
    if isinstance(value, str) and value.lstrip().startswith(("=", "+", "-", "@", "\t", "\r")):
        return "'" + value
    return value


@app.get("/api/admin/video/status")
def video_status(request: Request):
    require_session(request)
    local_file = not IS_VERCEL and VIDEO_PATH.is_file()
    return {
        "uploaded": bool(VIDEO_URL) or local_file,
        "size": VIDEO_PATH.stat().st_size if local_file else 0,
        "external_only": IS_VERCEL,
        "external_url": bool(VIDEO_URL),
    }


@app.put("/api/admin/video")
async def upload_video(request: Request):
    require_write(request)
    if IS_VERCEL:
        raise HTTPException(501, "Na Vercel, hospede o MP4 em armazenamento externo e use URL direta no painel.")
    if request.headers.get("content-type", "").split(";", 1)[0] != "video/mp4":
        raise HTTPException(415, "Envie um arquivo MP4.")
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    temporary = DATA_DIR / f"upload-{uuid.uuid4().hex}.tmp"
    size = 0
    try:
        with temporary.open("wb") as output:
            async for chunk in request.stream():
                size += len(chunk)
                if size > MAX_VIDEO_BYTES:
                    raise HTTPException(413, "O MP4 deve ter até 250 MB.")
                output.write(chunk)
        with temporary.open("rb") as uploaded:
            if uploaded.read(12)[4:8] != b"ftyp":
                raise HTTPException(400, "O arquivo não parece ser um MP4 válido.")
        temporary.replace(VIDEO_PATH)
    finally:
        temporary.unlink(missing_ok=True)
    return {"ok": True, "size": size}


@app.get("/media/campaign.mp4")
def campaign_video():
    if VIDEO_URL:
        parsed = urlparse(VIDEO_URL)
        if parsed.scheme != "https" or not parsed.netloc:
            raise HTTPException(503, "LUME_VIDEO_URL precisa ser uma URL HTTPS direta do MP4.")
        return RedirectResponse(VIDEO_URL, status_code=307, headers={"Cache-Control": "public, max-age=300"})
    if IS_VERCEL:
        raise HTTPException(404, "Configure LUME_VIDEO_URL ou uma URL direta de MP4 no painel.")
    if not VIDEO_PATH.is_file():
        raise HTTPException(404)
    return FileResponse(VIDEO_PATH, media_type="video/mp4", headers={"Cache-Control": "public, max-age=3600"})


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", nargs="?", default="serve", choices=("serve", "bootstrap-admin"))
    parser.add_argument("--email")
    args = parser.parse_args()
    if args.command == "bootstrap-admin":
        bootstrap_admin(args.email or input("E-mail do administrador: "))
    else:
        import uvicorn
        uvicorn.run("server:app", host=os.getenv("HOST", "127.0.0.1"), port=int(os.getenv("PORT", "8765")), workers=1)
